In [ ]:
import numpy as np
from copy import deepcopy

In [ ]:
def sphere(x):
  total = 0
  for i in x:
    total+=i**2

  return total

In [ ]:
x = (1,2,3)

In [ ]:
class problem:
  def __init__(self):
    self.number_of_genes = 8
    self.max_value = 10
    self.min_value = -10
    self.cost_function = sphere

In [ ]:
sphere(x)

14

In [ ]:
class individual:
  def __init__(self, prob):
    self.chromosome = np.random.uniform(prob.min_value, prob.max_value, prob.number_of_genes)
    self.cost = prob.cost_function(self.chromosome)

  def mutate(self, rate_of_gene_mutation, range_of_mutation):
    for index in range(len(self.chromosome)):
      if np.random.uniform() < rate_of_gene_mutation:
        self.chromosome[index] == np.random.randn() * range_of_mutation

  def crossover(self, parent2, explore_crossover):
    alpha = np.random.uniform(-explore_crossover, 1 + explore_crossover)
    child1 = deepcopy(self)
    child2 = deepcopy(parent2)
    child1.chromosome = alpha * self.chromosome + (1-alpha) * parent2.chromosome
    child2.chromosome = alpha * parent2.chromosome + (1-alpha) * self.chromosome

    return child1, child2

In [ ]:
p1 = problem()

In [ ]:
ind1 = individual(p1)

In [ ]:
ind2 = individual(p1)

In [ ]:
ind1.chromosome

array([-7.92810656, -5.2443076 , -9.28088458, -2.09309229,  0.02063635,
        1.06864416, -6.9101347 ,  7.33190362])

In [ ]:
ind2.chromosome

array([-8.25587415, -0.93613661, -4.90255699,  3.67553717,  5.81857654,
       -2.33621462,  3.00679283, -8.46134336])

In [ ]:
ind1.cost

283.52268829900987

In [ ]:
ind2.cost

226.52931458580537

In [ ]:
c1, c2 = ind1.crossover(ind2, .3)

In [ ]:
c1.chromosome

array([ -8.3009777 ,  -0.34329641,  -4.30006265,   4.46934862,
         6.61642139,  -2.80475154,   4.37144465, -10.63462567])

In [ ]:
c2.chromosome

array([-7.88300301, -5.8371478 , -9.88337892, -2.88690374, -0.7772085 ,
        1.53718108, -8.27478652,  9.50518593])

In [ ]:
class parameters:
  def __init__(self):
    self.population = 1000
    self.number_of_generations = 100
    self.child_rate_per_generation = 1
    self.crossover_explore_rate = .2
    self.rate_of_gene_mutation = .25
    self.range_of_gene_mutation = .5

In [ ]:
par1 = parameters()

In [ ]:
def choose_indices_from(list_size):
  index_1 = np.random.randint(list_size)
  index_2 = np.random.randint(list_size)

  if index_1 == index_2:
    return choose_indices_from(list_size)

  return index_1, index_2

In [ ]:
def run_genetic(prob, params):
  #Read in important info
  cost_function = prob.cost_function
  number_in_population = params.population
  max_number_of_generations = params.number_of_generations
  number_of_children_per_generation = params.child_rate_per_generation * number_in_population
  explore_crossover = params.crossover_explore_rate
  mutate_rate = params.rate_of_gene_mutation
  mutate_range = params.range_of_gene_mutation

  #Generate initial population
  population = []

  #Placeholder for best solution
  best_solution = individual(p1)
  best_solution.cost = np.infty

  #Populate the population
  for i in range(number_in_population):
    new_individual = individual(p1)
    population.append(new_individual)

  #Find best individual
  if new_individual.cost < best_solution.cost:
    best_solution = deepcopy(new_individual)

  #Generational Iteration
  for _iteration in range(max_number_of_generations):
    #Create children
    children = []

    while len(children) < number_of_children_per_generation:
      parent1_index, parent2_index = choose_indices_from(len(population))
      parent1 = population[parent1_index]
      parent2 = population[parent2_index]

      #Get children
      c1, c2 = parent1.crossover(parent2, explore_crossover)
      c1.mutate(mutate_rate, mutate_range)
      c2.mutate(mutate_rate, mutate_range)

      #Calculate cost
      c1.cost = cost_function(c1.chromosome)
      c2.cost = cost_function(c2.chromosome)

      #Add children to list of children
      children.append(c1)
      children.append(c2)

    #All children created.

    #Add children to population
    population += children

    #Sort the population
    population = sorted(population, key = lambda x: x.cost)

    #Cull the population
    population = population[:number_in_population]

    #Adjust the best solution
    if population[0].cost < best_solution.cost:
      best_solution = deepcopy(population[0])

    print("Best Solution for iteration " + str(_iteration) + " has cost of " + str(best_solution.cost))

  return best_solution

In [ ]:
bs = run_genetic(p1, par1)

Best Solution for iteration 0 has cost of 11.373632970141982
Best Solution for iteration 1 has cost of 11.373632970141982
Best Solution for iteration 2 has cost of 7.450441141097884
Best Solution for iteration 3 has cost of 5.7542500876092495
Best Solution for iteration 4 has cost of 3.637832648943064
Best Solution for iteration 5 has cost of 1.1164753485614216
Best Solution for iteration 6 has cost of 1.1015732415875197
Best Solution for iteration 7 has cost of 0.5993186746679756
Best Solution for iteration 8 has cost of 0.5993186746679756
Best Solution for iteration 9 has cost of 0.20706153730502308
Best Solution for iteration 10 has cost of 0.15484793392404542
Best Solution for iteration 11 has cost of 0.1225264327783014
Best Solution for iteration 12 has cost of 0.07465518970105461
Best Solution for iteration 13 has cost of 0.07465518970105461
Best Solution for iteration 14 has cost of 0.07465518970105461
Best Solution for iteration 15 has cost of 0.04369238765121556
Best Solution 

In [ ]:
bs.cost

3.150994872205296e-05

In [ ]:
bs.chromosome

array([-0.0013034 , -0.00189746,  0.00063714, -0.0019128 , -0.00015282,
       -0.00058047,  0.00142965, -0.00444317])